// Generated by CodeGen
package demo.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
public class User {

    /**
     *  主键ID
     */
    @Schema(description = "主键ID")
    private Long id;
    /**
     *  用户名
     */
    @Schema(description = "用户名")
    private String name;
}