package cn.xuqiudong.basic.third.inbound.model;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * Request for applying an inbound access token.
 *
 * @author Vic.xu
 */
@Data
@Accessors(chain = true)
@EqualsAndHashCode(callSuper = true)
public class TokenApplyRequest extends TokenSignPayload {

    /**
     * Signature generated by third-party private key.
     */
    private String sign;
}
