#\u4EE3\u7801\u751F\u6210\u5668\uFF0C\u914D\u7F6E\u4FE1\u606F

# \u6570\u636E\u5E93\u7C7B\u578B \u9ED8\u8BA4mysql\uFF0C\u6682\u65F6\u53EA\u652F\u6301mysql\u548Coracle
generator.database=mysql
#\u4F5C\u8005
generator.author=Vic.xu

#\u8868\u524D\u7F00\uFF0C\u751F\u6210\u5B9E\u4F53\u7684\u65F6\u5019\u4F1A\u53BB\u6389
generator.tablePrefix=T_

#\u5728\u5B9E\u4F53\u4E2D\u5FFD\u7565\u7684\u8868\u5B57\u6BB5\uFF0C\u4E00\u822C\u653E\u5728BaseEntity\u4E2D
generator.ignores=id,is_enable,is_delete,create_time,update_time,create_id,update_id
# \u5927\u6570\u636E\u7C7B\u578B\uFF1A\u4E0D\u5728list\u9875\u9762\u67E5\u8BE2\u7684\u6570\u636E
generator.textTypes=text,longtext,blob,longblob

###\u9700\u8981\u586B\u5145\u7684\u6570\u636E\u6A21\u677F
generator.templates[0]=generator/templates/Entity.java.vm
generator.templates[1]=generator/templates/Mapper.java.vm
generator.templates[2]=generator/templates/Mapper.xml.vm
generator.templates[3]=generator/templates/Service.java.vm
generator.templates[4]=generator/templates/Controller.java.vm
generator.templates[5]=generator/templates/list.html.vm
generator.templates[6]=generator/templates/form.html.vm

### \u6570\u636E\u5E93\u7C7B\u578B\u548Cjava\u6570\u636E\u7C7B\u578B\u7684\u5339\u914D\u5173\u7CFB\uFF0C\u4E0B\u9762\u662F\u9ED8\u8BA4\u7684\u5339\u914D\u5173\u7CFB\uFF0C\u53EF\u4EE5\u8FFD\u52A0\u6216\u8986\u76D6
#generator.dataTypeConvert.tinyint=Integer
#generator.dataTypeConvert.smallint=Inteer
#generator.dataTypeConvert.mediumint=Integer
#generator.dataTypeConvert.int=Integer
#generator.dataTypeConvert.integer=Integer
#generator.dataTypeConvert.number=Integer

#generator.dataTypeConvert.bigint=Long
#generator.dataTypeConvert.float=Float
#generator.dataTypeConvert.double=Double
#generator.dataTypeConvert.decimal=BigDecimal
#generator.dataTypeConvert.bit=Boolean
#generator.dataTypeConvert.enum=String
#
#generator.dataTypeConvert.char=String
#generator.dataTypeConvert.varchar=String
#generator.dataTypeConvert.tinytext=String
#generator.dataTypeConvert.text=String
#generator.dataTypeConvert.mediumtext=String
#generator.dataTypeConvert.longtext=String
#generator.dataTypeConvert.blob=String 
#generator.dataTypeConvert.clob=String
#
#generator.dataTypeConvert.date=Date
#generator.dataTypeConvert.time=Date
#generator.dataTypeConvert.datetime=Date
#generator.dataTypeConvert.timestamp=Date